[tool.poetry]
name = "django-sql"
version = "0.1.0"
description = ""
authors = ["Oleg Zamesov <o.zamesov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.11"
django = "^5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
