# Generated by Django 5.1 on 2024-08-15 20:09


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='День')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.CharField(max_length=20, verbose_name='Название месяца')),
                ('day_of_month_no', models.IntegerField(verbose_name='Номер дня внутри месяца')),
                ('day_of_week_no', models.IntegerField(verbose_name='Название для недели')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Выходной или празничный')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия сотрудника')),
                ('gender', models.BooleanField(verbose_name='Под сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название партнера')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='Название города')),
                ('metro', models.CharField(max_length=50, verbose_name='Ближайшее метро')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.CharField(max_length=100, unique=True, verbose_name='Название сюжета')),
                ('complexity', models.IntegerField(default=1, verbose_name='Сложность квеста')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название квеста')),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.legend')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.location')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('price', models.IntegerField(verbose_name='Cтоимость игры')),
                ('game_has_passed', models.BooleanField(verbose_name='Игра состоялась')),
                ('is_full_complite', models.BooleanField(default=False, verbose_name='Полностью пройден')),
                ('time_duration', models.IntegerField(verbose_name='Вермя прохождения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.employee')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
